name: Terraform Destroy

on: 
  workflow_dispatch:
    inputs:
      wait-time:
        description: 'Tempo de espera entre o plan e o destroy: 30s, 5m, 1h'
        required: true
        default: '2m'

jobs:
  terraform:
    runs-on: ubuntu-20.04
    steps:

      - name: Instalando terraform
        run: |
          cd ~
          sudo apt update
          sudo apt install -y unzip wget
          sudo wget https://releases.hashicorp.com/terraform/1.0.8/terraform_1.0.8_linux_amd64.zip
          sudo unzip terraform_1.0.8_linux_amd64.zip
          sudo chmod +x terraform
          terraform --version

      - name: Checkout Respository
        uses: actions/checkout@v2
        with:
          ref: main
          path: cd ./repository-files/

      - name: Terraform Init
        env:
          ARM_CLIENT_ID: ${{ secrets.AZURE_AD_CLIENT_ID }}
          ARM_CLIENT_SECRET: ${{ secrets.AZURE_AD_CLIENT_SECRET }}
          ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          ARM_TENANT_ID: ${{ secrets.AZURE_AD_TENANT_ID }}
        run: cd cd ./repository-files/vm-azure/ && ls -la && ~/terraform init 

      - name: Terraform Plan
        env:
          ARM_CLIENT_ID: ${{ secrets.AZURE_AD_CLIENT_ID }}
          ARM_CLIENT_SECRET: ${{ secrets.AZURE_AD_CLIENT_SECRET }}
          ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          ARM_TENANT_ID: ${{ secrets.AZURE_AD_TENANT_ID }}
        run: cd cd ./repository-files/vm-azure/ && ~/terraform plan -destroy 

      - name: Tempo de espera antes do destroy
        run:  sleep  "${{ github.event.inputs.wait-time }}" || sleep "2m"

      - name: Terraform Destroy
        env:
          ARM_CLIENT_ID: ${{ secrets.AZURE_AD_CLIENT_ID }}
          ARM_CLIENT_SECRET: ${{ secrets.AZURE_AD_CLIENT_SECRET }}
          ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          ARM_TENANT_ID: ${{ secrets.AZURE_AD_TENANT_ID }}
        run: cd cd ./repository-files/vm-azure/ &&  ~/terraform apply -destroy -auto-approve 

      - name: Salvando o Backend TFState
        uses: actions-js/push@master
        with:
          github_token: ${{ secrets.PERSONAL_GITHUB_TOKEN }}
          directory: cd ./repository-files/vm-azure/
          message: Update backend.tfstate
          branch: master